### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by zachlysobey** [vyorkin-play/fetch-mock-example#1]
I'm trying to run this project, but it doesn't seem to be working:

I do a `npm install`, then try to `npm test`, and get the following output.

Any ideas?

```
[fetch-mock-example]> npm test

> fetch-mock-example@1.0.0 test /Users/lysobeyz/workspace/_scratch/fetch-mock-example
> karma start


START:
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.9
Time: 10ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
25 03 2016 14:52:46.396:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/tests/index.js' }
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.readFile (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/karma-webpack/index.js:160:3)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/karma/lib/server.js:314
    sockets.forEach(function (socket) {
            ^

TypeError: sockets.forEach is not a function
    at disconnectBrowsers (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/karma/lib/server.js:314:13)
    at process.<anonymous> (/Users/lysobeyz/workspace/_scratch/fetch-mock-example/node_modules/karma/lib/server.js:355:5)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:264:26)
npm ERR! Test failed.  See above for more details.
```

**Comment by vyorkin** [comment]
sorry, better late than never, yes, I've just checked – it doesn't work :(
its old as shit, but I'm not sure it was working at that time either 😝 
I've updated my comment there https://github.com/node-nock/nock/issues/409#issuecomment-163745441 and removed the link to this example
